name: Linting

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Check coding style
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - run: pip install cpplint
        - run: python docs/generate_lint_report.py

    lint-report:
        if: always()
        name: Lint Report as Artifact
        runs-on: ubuntu-latest
        needs: lint
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - run: pip install cpplint
        - run: python docs/generate_lint_report.py
        - uses: actions/upload-artifact@v4
          with:
            name: LINT_REPORT-${GITHUB_REF##*/}
            path: docs/
