name: Main CI

on: [push, pull_request]

jobs:
    build:
        name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
        runs-on: ${{ matrix.platform.os }}

        strategy:
            fail-fast: false
            matrix:
                platform:
                - { name: Windows VS2019, os: windows-2019  }
                - { name: Windows VS2022, os: windows-2022  }
                - { name: Linux GCC,      os: ubuntu-latest }
                - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
                - { name: macOS,          os: macos-latest  }
                config:
                - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
                - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

        steps:
        - name: Install Linux Dependencies
          if: runner.os == 'Linux'
          run: sudo apt-get update && sudo apt-get install libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev

        - uses: actions/checkout@v3

        - uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

        - name: Create build directory
          run: mkdir build |
                cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install -DIS_TESTING:BOOL=TRUE ${{matrix.platform.flags}} ${{matrix.config.flags}}

        - name: Build
          shell: bash
          run: cmake --build build --config Release

        - name: Install
          shell: bash
          run: cmake --install build --config Release

        - name: Test
          shell: bash
          run: cmake -P test.cmake
