name: Testing

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Linting"]
    types:
      - completed
  pull_request:
    types: [review_requested]

jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: ${{ matrix.platform.name }}
        runs-on: ${{ matrix.platform.os }}

        strategy:
            fail-fast: false
            matrix:
                platform:
                - { name: Windows VS2019, os: windows-2019  }
                - { name: Windows VS2022, os: windows-2022  }
                - { name: Linux GCC,      os: ubuntu-latest }
                - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
                - { name: macOS,          os: macos-latest  }

        steps:
        - name: Install Linux Dependencies
          if: runner.os == 'Linux'
          run: sudo apt-get update && sudo apt-get install libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev -y

        - uses: actions/checkout@v3

        - uses: webfactory/ssh-agent@v0.7.0
          with:
              ssh-private-key: ${{secrets.KLEO_ORG_SSH}}

        - name: Create build directory
          run: mkdir build |
                cmake -S . -B build -DIS_TESTING:BOOL=TRUE ${{matrix.platform.flags}}

        - name: Build
          shell: bash
          run: cmake --build build --config Release

        - name: Test
          shell: bash
          run: cmake -P tests/LaunchTests.cmake
